### ISSUE TITLE
dsr_distance.py没有 compute_dsr_dist 方法 和 少了一个 reid_losses 定义

### ISSUE THREAD

**Issue by nobody-cheng** [JDAI-CV/fast-reid#161]
你好，我在训练 PartialReID 的时候，提示没有 compute_dsr_dist 和 reid_losses 这两个定义，通过全局搜索也没有找到

compute_dsr_dist == get_dsr_dist ??
reid_losses 在以前版本找到了，修改后运行如下命令，会出现 config配置错误

CUDA_VISIBLE_DEVICES='1' python projects/PartialReID/train_net.py --config-file 'projects/PartialReID/configs/partial_market.yml'

```
Traceback (most recent call last):
  File "projects/PartialReID/train_net.py", line 80, in <module>
    main(args)
  File "projects/PartialReID/train_net.py", line 46, in main
    cfg = setup(args)
  File "projects/PartialReID/train_net.py", line 38, in setup
    cfg.merge_from_file(args.config_file)
  File "./fastreid/config/config.py", line 110, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "./fastreid/config/config.py", line 121, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/opt/conda/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/opt/conda/lib/python3.7/site-packages/yacs/config.py", line 464, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/opt/conda/lib/python3.7/site-packages/yacs/config.py", line 464, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/opt/conda/lib/python3.7/site-packages/yacs/config.py", line 464, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/opt/conda/lib/python3.7/site-packages/yacs/config.py", line 477, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.LOSSES.TRI.USE_COSINE_DIST'

```

```
DATALOADER:
  NAIVE_WAY: False
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  PK_SAMPLER: True
DATASETS:
  COMBINEALL: False
  NAMES: ('Market1501',)
  TESTS: ('Market1501',)
INPUT:
  DO_AUGMIX: False
  DO_AUTOAUG: False
  DO_CJ: False
  DO_FLIP: True
  DO_PAD: True
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: False
    MEAN: [151.98, 142.29000000000002, 126.735]
    PROB: 0.5
  RPT:
    ENABLED: False
    PROB: 0.5
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  BACKBONE:
    DEPTH: 50
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    NORM_SPLIT: 1
    PRETRAIN: True
    PRETRAIN_PATH:
    WITH_IBN: False
    WITH_NL: False
    WITH_SE: False
  DEVICE: cuda
  FREEZE_LAYERS: ['']
  HEADS:
    CLS_LAYER: linear
    IN_FEAT: 2048
    MARGIN: 0.15
    NAME: BNneckHead
    NECK_FEAT: before
    NORM: BN
    NORM_SPLIT: 1
    NUM_CLASSES: 0
    POOL_LAYER: avgpool
    REDUCTION_DIM: 512
    SCALE: 128
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.0
      SCALE: 1.0
    CIRCLE:
      ALPHA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME: ('CrossEntropyLoss',)
    TRI:
      HARD_MINING: True
      MARGIN: 0.3
      NORM_FEAT: False
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.120000000000005, 57.375]
  WEIGHTS:
OUTPUT_DIR: logs/
SOLVER:
  BASE_LR: 0.0003
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  DELAY_ITERS: 0
  ETA_MIN_LR: 3e-07
  FREEZE_ITERS: 0
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  MAX_ITER: 40000
  MOMENTUM: 0.9
  OPT: Adam
  SCHED: WarmupMultiStepLR
  STEPS: [30, 55]
  SWA:
    ENABLED: False
    ETA_MIN_LR: 3.5e-06
    ITER: 10
    LR_FACTOR: 10.0
    LR_SCHED: False
    PERIOD: 2
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: False
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 50
  IMS_PER_BATCH: 128
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: False
    NUM_ITER: 300
  RERANK:
    ENABLED: False
    K1: 20
    K2: 6
    LAMBDA: 0.3
```
谢谢

**Comment by nobody-cheng** [comment]
CUDA_VISIBLE_DEVICES='1' python projects/PartialReID/train_net.py --config-file 'projects/PartialReID/configs/partial_market.yml'
```
DATALOADER:
  NAIVE_WAY: False
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  PK_SAMPLER: True
DATASETS:
  COMBINEALL: False
  NAMES: ('Market1501',)
  TESTS: ('Market1501',)
INPUT:
  DO_AUGMIX: False
  DO_AUTOAUG: False
  DO_CJ: False
  DO_FLIP: True
  DO_PAD: True
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: False
    MEAN: [151.98, 142.29000000000002, 126.735]
    PROB: 0.5
  RPT:
    ENABLED: False
    PROB: 0.5
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  BACKBONE:
    DEPTH: 50
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    NORM_SPLIT: 1
    PRETRAIN: True
    PRETRAIN_PATH:
    WITH_IBN: False
    WITH_NL: False
    WITH_SE: False
  DEVICE: cuda
  FREEZE_LAYERS: ['']
  HEADS:
    CLS_LAYER: linear
    IN_FEAT: 2048
    MARGIN: 0.15
    NAME: BNneckHead
    NECK_FEAT: before
    NORM: BN
    NORM_SPLIT: 1
    NUM_CLASSES: 0
    POOL_LAYER: avgpool
    REDUCTION_DIM: 512
    SCALE: 128
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.0
      SCALE: 1.0
    CIRCLE:
      ALPHA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME: ('CrossEntropyLoss',)
    TRI:
      HARD_MINING: True
      MARGIN: 0.3
      NORM_FEAT: False
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.120000000000005, 57.375]
  WEIGHTS:
OUTPUT_DIR: logs/
SOLVER:
  BASE_LR: 0.0003
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  DELAY_ITERS: 0
  ETA_MIN_LR: 3e-07
  FREEZE_ITERS: 0
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  MAX_ITER: 40000
  MOMENTUM: 0.9
  OPT: Adam
  SCHED: WarmupMultiStepLR
  STEPS: [30, 55]
  SWA:
    ENABLED: False
    ETA_MIN_LR: 3.5e-06
    ITER: 10
    LR_FACTOR: 10.0
    LR_SCHED: False
    PERIOD: 2
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: False
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 50
  IMS_PER_BATCH: 128
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: False
    NUM_ITER: 300
  RERANK:
    ENABLED: False
    K1: 20
    K2: 6
    LAMBDA: 0.3
```
