### ISSUE TITLE
mgn可视化ROC曲线差

### ISSUE THREAD

**Issue by nobody-cheng** [JDAI-CV/fast-reid#172]
使用如下配置训练模型 R50-IBN
```
CUDNN_BENCHMARK: true
DATALOADER:
  NAIVE_WAY: false
  NUM_INSTANCE: 16
  NUM_WORKERS: 0
  PK_SAMPLER: true
DATASETS:
  COMBINEALL: false
  NAMES:
  - Market1501
  TESTS:
  - Market1501
INPUT:
  DO_AUGMIX: false
  DO_AUTOAUG: true
  DO_CJ: false
  DO_FLIP: true
  DO_PAD: true
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: true
    MEAN:
    - 123.675
    - 116.28
    - 103.53
    PROB: 0.5
  RPT:
    ENABLED: false
    PROB: 0.5
  SIZE_TEST:
  - 384
  - 128
  SIZE_TRAIN:
  - 384
  - 128
MODEL:
  BACKBONE:
    DEPTH: 50
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    NORM_SPLIT: 1
    PRETRAIN: true
    PRETRAIN_PATH: ./checkpoints/resnet50_ibn_a.pth.tar
    WITH_IBN: true
    WITH_NL: true
    WITH_SE: false
  HEADS:
    CLS_LAYER: circle
    IN_FEAT: 2048
    MARGIN: 0.35
    NAME: BNneckHead
    NECK_FEAT: after
    NORM: BN
    NORM_SPLIT: 1
    NUM_CLASSES: 751
    POOL_LAYER: gempool
    REDUCTION_DIM: 512
    SCALE: 64
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 1.0
    CIRCLE:
      ALPHA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    - TripletLoss
    TRI:
      HARD_MINING: true
      MARGIN: 0.0
      NORM_FEAT: false
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  OPEN_LAYERS:
  - heads
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.120000000000005
  - 57.375
  WEIGHTS: /data/share/imageAlgorithm/zhangcheng/code/fast-reid/logs/market1501/bagtricks_R50-ibn/model_final.pth
OUTPUT_DIR: logs/market1501/bagtricks_R50-ibn
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 6000
  DELAY_ITERS: 9000
  ETA_MIN_LR: 7.7e-07
  FREEZE_ITERS: 2000
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  LOG_PERIOD: 200
  MAX_ITER: 18000
  MOMENTUM: 0.9
  OPT: Adam
  SCHED: DelayedCosineAnnealingLR
  STEPS:
  - 30
  - 55
  SWA:
    ENABLED: false
    ETA_MIN_LR: 3.5e-06
    ITER: 0
    LR_FACTOR: 10.0
    LR_SCHED: false
    PERIOD: 10
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 2000
  IMS_PER_BATCH: 256
  METRIC: cosine
  PRECISE_BN:
    DATASET: DukeMTMC
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3
```
指标如下：
![eval](https://user-images.githubusercontent.com/34908468/87395695-5ce5c980-c5e4-11ea-8322-a21860924de9.jpg)
可视化如下，结果很不错：
![pos_neg_dist](https://user-images.githubusercontent.com/34908468/87395586-30ca4880-c5e4-11ea-8d11-823fc09040fd.jpg)
![roc](https://user-images.githubusercontent.com/34908468/87395600-32940c00-c5e4-11ea-85d0-0b67a8541807.jpg)
=====================================
但是如下配置训练模型 局部特征 mgn-R50-IBN，指标好，但可视化差，实际使用特征比对容易误识别，由于显卡配置，batchsize：48
```
CUDNN_BENCHMARK: true
DATALOADER:
  NAIVE_WAY: false
  NUM_INSTANCE: 16
  NUM_WORKERS: 0
  PK_SAMPLER: true
DATASETS:
  COMBINEALL: false
  NAMES:
  - Market1501
  TESTS:
  - Market1501
INPUT:
  DO_AUGMIX: false
  DO_AUTOAUG: true
  DO_CJ: false
  DO_FLIP: true
  DO_PAD: true
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: true
    MEAN:
    - 123.675
    - 116.28
    - 103.53
    PROB: 0.5
  RPT:
    ENABLED: false
    PROB: 0.5
  SIZE_TEST:
  - 384
  - 128
  SIZE_TRAIN:
  - 384
  - 128
MODEL:
  BACKBONE:
    DEPTH: 50
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    NORM_SPLIT: 1
    PRETRAIN: true
    PRETRAIN_PATH: ./checkpoints/resnet50_ibn_a.pth.tar
    WITH_IBN: true
    WITH_NL: true
    WITH_SE: false
  HEADS:
    CLS_LAYER: circle
    IN_FEAT: 256
    MARGIN: 0.35
    NAME: BNneckHead
    NECK_FEAT: after
    NORM: BN
    NORM_SPLIT: 1
    NUM_CLASSES: 751
    POOL_LAYER: gempool
    REDUCTION_DIM: 512
    SCALE: 64
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 0.125
    CIRCLE:
      ALPHA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    - TripletLoss
    TRI:
      HARD_MINING: true
      MARGIN: 0.0
      NORM_FEAT: false
      SCALE: 0.2
  META_ARCHITECTURE: MGN
  OPEN_LAYERS:
  - b1_pool
  - b1_head
  - b2_pool
  - b2_head
  - b21_pool
  - b21_head
  - b22_pool
  - b22_head
  - b3_pool
  - b3_head
  - b31_pool
  - b31_head
  - b32_pool
  - b32_head
  - b33_pool
  - b33_head
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.120000000000005
  - 57.375
  WEIGHTS: ''
OUTPUT_DIR: logs/market1501/mgn_R50-ibn
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.0
  CHECKPOINT_PERIOD: 6000
  DELAY_ITERS: 9000
  ETA_MIN_LR: 7.7e-07
  FREEZE_ITERS: 2000
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 48
  LOG_PERIOD: 200
  MAX_ITER: 18000
  MOMENTUM: 0.9
  OPT: Adam
  SCHED: DelayedCosineAnnealingLR
  STEPS:
  - 30
  - 55
  SWA:
    ENABLED: false
    ETA_MIN_LR: 3.5e-06
    ITER: 0
    LR_FACTOR: 10.0
    LR_SCHED: false
    PERIOD: 10
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 2000
  IMS_PER_BATCH: 32
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3
```
mgn指标如下：
![eval_mgn](https://user-images.githubusercontent.com/34908468/87396468-79363600-c5e5-11ea-9330-f2cbc5528ea6.jpg)
mgn可视化如下，结果如下：
![roc](https://user-images.githubusercontent.com/34908468/87396586-a08d0300-c5e5-11ea-928e-c0a8cb44b1ff.jpg)
![pos_neg_dist](https://user-images.githubusercontent.com/34908468/87396590-a256c680-c5e5-11ea-9694-4d94cc37ba64.jpg)

我只是替换了config文件，代码并未做修改
