### ISSUE TITLE
how to modify "PRECISE_BN"

### ISSUE THREAD

**Issue by yyyyykp** [JDAI-CV/fast-reid#278]
I trained with " ./tools/train_net.py --config-file ./configs/My_Datasets/bagtricks_R50.yml MODEL.DEVICE "cuda:0" ".
The following is part of the output: 
```
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: False
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 30
  IMS_PER_BATCH: 128
  METRIC: cosine
  PRECISE_BN:    #<--this
    DATASET: Market1501
    ENABLED: False
    NUM_ITER: 300
  RERANK:
    ENABLED: False
    K1: 20
    K2: 6
    LAMBDA: 0.3
  ROC_ENABLED: False
```
Excuse me, what does "PRECISE_BN" mean, and where can I modify it?
