### ISSUE TITLE
Stuck in "starting training from iteraton 0" when training my data using sbs_r101-bin.yml

### ISSUE THREAD

**Issue by LifeIsSoSolong** [JDAI-CV/fast-reid#289]
## Code I wrote
```
(1)clone latest code 2020.9.28
(2)prepare my own dataset 
(3)write and register new dataset class
(4)write my own yml
(5)run train command
```
## Command I Run and Problem I counter
(1)train using bot
```python tools/train_net.py --config-file configs/myown/bagtricks_R50.yml --num-gpus 8```

When I use bot to train my own data, it works normally(train / val / test  all work well).

(2)train using sbs
```python tools/train_net.py --config-file configs/myown/sbs_R101-ibn.yml --num-gpus 8```

BUG::When i use sbs_r101-ibn.yml to train my data, it stucked in "starting training from iteraton 0" with no any error.

## My sbs_R101-ibn.yml
```
_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True
    PRETRAIN: True
    PRETRAIN_PATH: "/home/projects/fast-reid/checkpoints/resnet101_ibn_a-59ea0ac6.pth"

DATASETS:
  NAMES: ("MyTrain",)
  TESTS: ("MyTrain",)

SOLVER:
  MAX_ITER: 500
  STEPS: [120,240]
  CHECKPOINT_PERIOD: 50
  IMS_PER_BATCH: 64
TEST:
  EVAL_PERIOD: 50
  IMS_PER_BATCH: 64

OUTPUT_DIR: "logs/myown/sbs_R101-ibn"
```
##  Train log (Stuck in train iteration 0)
```
***
  (heads): EmbeddingHead(
    (pool_layer): GeneralizedMeanPoolingP(Parameter containing:
    tensor([3.], device='cuda:0', requires_grad=True), output_size=1)
    (bottleneck): Sequential(
      (0): BatchNorm(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (classifier): CircleSoftmax(in_features=2048, num_classes=19658, scale=64, margin=0.35)
  )
)
[09/28 11:04:57] fastreid.engine.defaults INFO: Freeze layer group "backbone" training for 11370 iterations
[09/28 11:04:58] fastreid.utils.checkpoint INFO: No checkpoint found. Training model from scratch
[09/28 11:04:58] fastreid.engine.train_loop INFO: Starting training from iteration 0
```

## Expected behavior:
When I use bot to train my own data, it works normally, after log"starting training from iteraton 0", it will print train iter log like this:
"[09/29 01:46:45] fastreid.engine.train_loop INFO: Starting training from iteration 0
[09/29 01:48:06] fastreid.utils.events INFO:  eta: 1 day, 15:18:51  iter: 199  total_loss: 9.984  loss_cls: 9.886  loss_triplet: 0.09578  time: 0.3753  data_time: 0.0073  lr: 9.56e-06  max_mem: 3478M"
********

But when I use sbs_r101-ibn to train , it stucks in fastreid.engine.train_loop INFO: Starting training from iteration 0
