### ISSUE TITLE
多卡训练GPU利用率不均衡问题

### ISSUE THREAD

**Issue by merlinarer** [JDAI-CV/fast-reid#294]
你好，我在用4个GPU跑模型的时候，开始会发现卡0会开4个进程并且利用率会达到100%，其他卡则利用率很低，如下图
![捕获](https://user-images.githubusercontent.com/71754029/94775657-d70f3880-03f2-11eb-978f-3628abf33cdd.PNG)
通过在build_model函数加打印信息，发现程序长时间卡在model build之后
```

    @classmethod
    def build_model(cls, cfg):
        """
        Returns:
            torch.nn.Module:
        It now calls :func:`fastreid.modeling.build_model`.
        Overwrite it if you'd like a different model.
        """
        model = build_model(cfg)
        # logger = logging.getLogger(__name__)
        # logger.info("Model:\n{}".format(model))
        print("model built")
        return model
```
![捕获1](https://user-images.githubusercontent.com/71754029/94776370-3588e680-03f4-11eb-93fd-5024763e1c8e.PNG)

我的运行命令是
`CUDA_VISIBLE_DEVICES=0,1,2,3` python ./tools/train_net.py --config-file configs/Digix/sbs_R101-ibn.yml --num-gpus 4

设置为：
```
>CUDNN_BENCHMARK: true
DATALOADER:
  NAIVE_WAY: true
  NUM_INSTANCE: 16
  NUM_WORKERS: 8
  PK_SAMPLER: true
DATASETS:
  COMBINEALL: false
  NAMES:
  - Digix
  TESTS:
  - Digix
INPUT:
  CJ:
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    ENABLED: true
    HUE: 0.1
    PROB: 0.8
    SATURATION: 0.1
  DO_AUGMIX: false
  DO_AUTOAUG: true
  DO_FLIP: true
  DO_PAD: true
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: true
    MEAN:
    - 123.675
    - 116.28
    - 103.53
    PROB: 0.5
  RPT:
    ENABLED: false
    PROB: 0.5
  Rotate:
    Do_Rotation: false
    PROB: 0.6
  SIZE_TEST:
  - 448
  - 448
  SIZE_TRAIN:
  - 448
  - 448
MODEL:
  BACKBONE:
    DEPTH: 101x
    FEAT_DIM: 2048
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    PRETRAIN: true
    PRETRAIN_PATH: /home/workspace/merlin/projects/digix/fast-reid/pretrained/resnet101_ibn_a-59ea0ac6.pth
    WITH_IBN: true
    WITH_NL: false
    WITH_SE: false
  DEVICE: cuda:0
  FREEZE_LAYERS:
  - backbone
  HEADS:
    CLS_LAYER: circleSoftmax
    EMBEDDING_DIM: 512
    MARGIN: 0.35
    NAME: EmbeddingHead
    NECK_FEAT: after
    NORM: BN
    NUM_CLASSES: 0
    POOL_LAYER: gempoolP
    SCALE: 64
    WITH_BNNECK: true
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 1.0
    CIRCLE:
      ALPHA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    - CircleLoss
    TRI:
      HARD_MINING: true
      MARGIN: 0.0
      NORM_FEAT: false
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.120000000000005
  - 57.375
  WEIGHTS: ''
OUTPUT_DIR: logs/digix/sbs_R101-ibn
SOLVER:
  AMP_ENABLED: true
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 30
  DELAY_ITERS: 30
  ETA_MIN_LR: 7.7e-07
  FREEZE_ITERS: 10
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  MAX_ITER: 60
  MOMENTUM: 0.9
  OPT: Adam
  SCHED: WarmupCosineAnnealingLR
  STEPS:
  - 40
  - 90
  SWA:
    ENABLED: false
    ETA_MIN_LR: 3.5e-06
    ITER: 10
    LR_FACTOR: 10.0
    LR_SCHED: false
    PERIOD: 2
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 30
  IMS_PER_BATCH: 128
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3
  ROC_ENABLED: false
```
一直不知道什么原因，希望得到你的帮助，谢谢！
