### ISSUE TITLE
failed to reach the mAP mentioned in the paper

### ISSUE THREAD

**Issue by YZY-lucky** [JDAI-CV/fast-reid#384]
Dear Mr. Liao, for the Veri-Wild data set of Fastreid, we have tried many times but failed to reach the mAP mentioned in the paper. The best one of mine is 5% less than yours.Would you please give me some advice on how to improve the mAP to your current level?

[ Datasets               | Rank-1   | Rank-5   | Rank-10   | mAP     | mINP   |
| -- | -- | --| --| -- | -- |
| SmallVeRiWild      | 94.85%   | 98.29%   | 99.16%    | 81.24% | 56.50% |
| MediumVeRiWild | 93.19%   | 97.57%   | 98.45%    | 75.86% | 46.80% |
| LargeVeRiWild      | 90.11%   | 95.96%   | 97.61%    | 68.37% | 35.31% |

**Comment by L1aoXingyu** [comment]
Recently, the fastreid code has been refactored and changed a lot. We will try it later.

**Comment by lxc86739795** [comment]
We just updated the training config on VeRi-Wild. Please try it.

**Comment by kishansairam9** [comment]
Latest config (819c5a8ab4f1b36f78f9874f85e77f3ac5ea2b9a) also has the same issue.

Following was obtained with 4x 2080Ti
| Datasets       | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
|:---------------|:---------|:---------|:----------|:------|:-------|:---------|
| SmallVeRiWild  | 94.11    | 98.16    | 98.69     | 76.70 | 48.80  | 85.41    |
| MediumVeRiWild | 92.33    | 97.09    | 98.23     | 70.87 | 38.95  | 81.60    |
| LargeVeRiWild  | 89.30    | 95.29    | 97.09     | 63.08 | 27.81  | 76.19    |

This was obtained using 2x V100
| Datasets       | Rank-1   | Rank-5   | Rank-10   | mAP   | mINP   | metric   |
|:---------------|:---------|:---------|:----------|:------|:-------|:---------|
| SmallVeRiWild  | 94.54    | 98.36    | 99.10     | 79.45 | 53.22  | 87.00    |
| MediumVeRiWild | 93.17    | 97.41    | 98.41     | 74.08 | 43.71  | 83.63    |
| LargeVeRiWild  | 90.05    | 95.96    | 97.38     | 66.45 | 32.14  | 78.25    |

@lxc86739795

**Comment by lxc86739795** [comment]
> Latest config ([819c5a8](https://github.com/JDAI-CV/fast-reid/commit/819c5a8ab4f1b36f78f9874f85e77f3ac5ea2b9a)) also has the same issue.
> 
> Following was obtained with 4x 2080Ti
> 
> Datasets	Rank-1	Rank-5	Rank-10	mAP	mINP	metric
> SmallVeRiWild	94.11	98.16	98.69	76.70	48.80	85.41
> MediumVeRiWild	92.33	97.09	98.23	70.87	38.95	81.60
> LargeVeRiWild	89.30	95.29	97.09	63.08	27.81	76.19
> This was obtained using 2x V100
> 
> Datasets	Rank-1	Rank-5	Rank-10	mAP	mINP	metric
> SmallVeRiWild	94.54	98.36	99.10	79.45	53.22	87.00
> MediumVeRiWild	93.17	97.41	98.41	74.08	43.71	83.63
> LargeVeRiWild	90.05	95.96	97.38	66.45	32.14	78.25
> @lxc86739795

This is my log file:
[veriwild_log_bagtricks_R50-ibn_4gpu.txt](https://github.com/JDAI-CV/fast-reid/files/6073483/veriwild_log_bagtricks_R50-ibn_4gpu.txt)

Line 0\~1619 is the training log. Line 1620\~end is one test procedure.
You can check the difference between your config and my config.
@kishansairam9

**Comment by lxc86739795** [comment]
It seems that my latest update is not merged into the new config.
Please refer to my log file. @kishansairam9 @YZY-lucky

**Comment by kishansairam9** [comment]
Thank you @lxc86739795. Main difference is in number of epochs 60 vs 120, so the difference makes sense

This is the updated config as per file you sent. I've started the training, I'll let you know once it's done.
```yaml
_BASE_: ../Base-bagtricks.yml

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True

  HEADS:
    POOL_LAYER: gempool

  LOSSES:
    TRI:
      HARD_MINING: False
      MARGIN: 0.0

DATASETS:
  NAMES: ("VeRiWild",)
  TESTS: ("SmallVeRiWild", "MediumVeRiWild", "LargeVeRiWild",)

SOLVER:
  IMS_PER_BATCH: 128
  MAX_EPOCH: 120
  STEPS: [30, 70, 90]
  BIAS_LR_FACTOR: 1.0
  ETA_MIN_LR: 0.0000003
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5000

  CHECKPOINT_PERIOD: 20

TEST:
  EVAL_PERIOD: 20
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/veriwild/bagtricks_R50-ibn_4gpu
```
