### ISSUE TITLE
人脸识别学习率导致精度突降

### ISSUE THREAD

**Issue by nobody-cheng** [JDAI-CV/fast-reid#386]
训练过程中学习率变化导致精度下降，是我配置错了吗
![image](https://user-images.githubusercontent.com/34908468/105270964-9cafee00-5bd1-11eb-9f83-c00f03b6ac21.png)

训练文件配置config.yanl
```
CUDNN_BENCHMARK: false
DATALOADER:
  NAIVE_WAY: true
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  PK_SAMPLER: false
DATASETS:
  COMBINEALL: false
  NAMES:
  - MS1MV2
  TESTS:
  - CPLFW
  - VGG2_FP
  - CALFW
  - CFP_FF
  - CFP_FP
  - AgeDB_30
  - LFW
INPUT:
  AUGMIX_PROB: 0.0
  AUTOAUG_PROB: 0.0
  CJ:
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    ENABLED: false
    HUE: 0.1
    PROB: 0.5
    SATURATION: 0.1
  DO_AFFINE: false
  DO_AUGMIX: false
  DO_AUTOAUG: false
  DO_FLIP: true
  DO_PAD: false
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: false
    PROB: 0.5
    VALUE:
    - 123.675
    - 116.28
    - 103.53
  RPT:
    ENABLED: false
    PROB: 0.5
  SIZE_TEST:
  - 112
  - 112
  SIZE_TRAIN:
  - 112
  - 112
KD:
  MODEL_CONFIG: ''
  MODEL_WEIGHTS: ''
MODEL:
  BACKBONE:
    DEPTH: 50x
    FEAT_DIM: 25088
    LAST_STRIDE: 1
    NAME: build_resnetIR_backbone
    NORM: BN
    PRETRAIN: true
    PRETRAIN_PATH: ''
    WITH_IBN: false
    WITH_NL: false
    WITH_SE: true
  DEVICE: cuda
  FREEZE_LAYERS:
  - ''
  HEADS:
    CLS_LAYER: circleSoftmax
    EMBEDDING_DIM: 512
    MARGIN: 0.25
    NAME: EmbeddingHead
    NECK_FEAT: after
    NORM: BN
    NUM_CLASSES: 85742
    POOL_LAYER: flatten
    SCALE: 256
    WITH_BNNECK: true
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.0
      SCALE: 1.0
    CIRCLE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    COSFACE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    TRI:
      HARD_MINING: true
      MARGIN: 0.3
      NORM_FEAT: false
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN:
  - 127.5
  - 127.5
  - 127.5
  PIXEL_STD:
  - 127.5
  - 127.5
  - 127.5
  QUEUE_SIZE: 8192
  WEIGHTS: ''
OUTPUT_DIR: projects/FastFace/logs/ir_se50-ms1mv2-circle
SOLVER:
  BASE_LR: 0.1
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 2
  DELAY_EPOCHS: 0
  ETA_MIN_LR: 0.0001
  FP16_ENABLED: false
  FREEZE_FC_ITERS: 0
  FREEZE_ITERS: 0
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  MAX_EPOCH: 16
  MOMENTUM: 0.9
  NESTEROV: true
  OPT: SGD
  SCHED: CosineAnnealingLR
  STEPS:
  - 30
  - 55
  WARMUP_EPOCHS: 1
  WARMUP_FACTOR: 0.1
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 2
  FLIP_ENABLED: false
  IMS_PER_BATCH: 64
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3
  ROC_ENABLED: false

```
