### ISSUE TITLE
Have you reproduced the accuracy of CircleLoss?

### ISSUE THREAD

**Issue by Kewenjing1020** [JDAI-CV/fast-reid#41]
I tried to use the implemented circleloss, but failed to reproduce the claimed accuracy in paper.

**Comment by L1aoXingyu** [comment]
you need to tune batch size with K=4, P=4, which means batch size is 16, with 4 identities and 4 images of each identity. Besides, it needs to freeze backbone for the first 2000 iters.
You can try on market151, I will put the `config.yaml` this weekend.

**Comment by L1aoXingyu** [comment]
![image](https://user-images.githubusercontent.com/19245504/80170815-6bdb6200-861b-11ea-9a76-993beb5d7a2f.png)
@Kewenjing1020 this is my reproduced results with config

```
MODEL:
  META_ARCHITECTURE: 'Baseline'

  OPEN_LAYERS: "heads"

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 50
    LAST_STRIDE: 1
    WITH_IBN: False
    WITH_NL: False
    PRETRAIN: True

  HEADS:
    NUM_CLASSES: 751
    NAME: "BNneckHead"
    CLS_LAYER: "circle"
    POOL_LAYER: "avgpool"
    SCALE: 128
    MARGIN: 0.25

  LOSSES:
    NAME: ("CrossEntropyLoss",)
    CE:
      EPSILON: 0.1
      SCALE: 1.0

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  REA:
    ENABLED: True
    PROB: 0.5
    MEAN: [123.675, 116.28, 103.53]
  DO_PAD: True


DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

SOLVER:
  OPT: "SGD"
  MAX_ITER: 24000
  BASE_LR: 0.01
  BIAS_LR_FACTOR: 2.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
  IMS_PER_BATCH: 16

  STEPS: [16000, 20000]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 4000
  FREEZE_ITERS: 4000

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 6000

TEST:
  EVAL_PERIOD: 4000
  IMS_PER_BATCH: 512

CUDNN_BENCHMARK: True

OUTPUT_DIR: "logs/market/circle_loss_sgd"

```

you can reproduce my results in `BagTricks` folder by
```
CUDA_VISIBLE_DEVICES=1 python train_net.py --config-file='circle_loss.yml'
```
