### ISSUE TITLE
mobilenetv2 推理精度预计能达到多少（veri数据集）

### ISSUE THREAD

**Issue by xuarehere** [JDAI-CV/fast-reid#655]
mobilenetv2 推理精度预计能达到多少？
下面几个是训练过程中的一些信息

![acc](https://user-images.githubusercontent.com/22950910/165034615-5886122b-d91d-45c7-8bfe-83f63301eb53.png)
![lr](https://user-images.githubusercontent.com/22950910/165034646-2a685d51-c3a6-46df-9f3a-14af85b54e23.png)

![map](https://user-images.githubusercontent.com/22950910/165034596-e3cee38a-150b-4960-9fd4-2bc0a3c1edb4.png)

目前 veri 数据集，Rank-1,我这边只能训到  93%

配置信息如下
```
CUDNN_BENCHMARK: true
DATALOADER:
  NUM_INSTANCE: 16
  NUM_WORKERS: 8
  SAMPLER_TRAIN: NaiveIdentitySampler
  SET_WEIGHT: []
DATASETS:
  COMBINEALL: false
  NAMES:
  - VeRi
  TESTS:
  - VeRi
INPUT:
  AFFINE:
    ENABLED: false
  AUGMIX:
    ENABLED: false
    PROB: 0.0
  AUTOAUG:
    ENABLED: true
    PROB: 0.1
  CJ:
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    ENABLED: false
    HUE: 0.1
    PROB: 0.5
    SATURATION: 0.1
  CROP:
    ENABLED: false
    RATIO:
    - 0.75
    - 1.3333333333333333
    SCALE:
    - 0.16
    - 1
    SIZE:
    - 224
    - 224
  FLIP:
    ENABLED: true
    PROB: 0.5
  PADDING:
    ENABLED: true
    MODE: constant
    SIZE: 10
  REA:
    ENABLED: true
    PROB: 0.5
    VALUE:
    - 123.675
    - 116.28
    - 103.53
  RPT:
    ENABLED: false
    PROB: 0.5
  SIZE_TEST:
  - 256
  - 256
  SIZE_TRAIN:
  - 256
  - 256
KD:
  EMA:
    ENABLED: false
    MOMENTUM: 0.999
  MODEL_CONFIG: []
  MODEL_WEIGHTS: []
MODEL:
  BACKBONE:
    ATT_DROP_RATE: 0.0
    DEPTH: 1.0x
    DROP_PATH_RATIO: 0.1
    DROP_RATIO: 0.0
    FEAT_DIM: 1280
    LAST_STRIDE: 1
    NAME: build_mobilenetv2_backbone
    NORM: BN
    PRETRAIN: false
    PRETRAIN_PATH: ''
    SIE_COE: 3.0
    STRIDE_SIZE:
    - 16
    - 16
    WITH_IBN: false
    WITH_NL: true
    WITH_SE: false
  DEVICE: cuda:0
  FREEZE_LAYERS:
  - backbone
  HEADS:
    CLS_LAYER: CircleSoftmax
    EMBEDDING_DIM: 0
    MARGIN: 0.35
    NAME: EmbeddingHead
    NECK_FEAT: after
    NORM: BN
    NUM_CLASSES: 576
    POOL_LAYER: GeneralizedMeanPoolingP
    SCALE: 64
    WITH_BNNECK: true
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 1.0
    CIRCLE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    COSFACE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    - TripletLoss
    TRI:
      HARD_MINING: true
      MARGIN: 0.0
      NORM_FEAT: false
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.120000000000005
  - 57.375
  QUEUE_SIZE: 8192
  WEIGHTS: model_best.pth
OUTPUT_DIR: logs/veri/mobilenetv2_v2
SOLVER:
  AMP:
    ENABLED: true
  BASE_LR: 0.00025
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 20
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 5.0
    ENABLED: false
    NORM_TYPE: 2.0
  DELAY_EPOCHS: 30
  ETA_MIN_LR: 7.0e-07
  FREEZE_ITERS: 1000
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 256
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: false
  OPT: SGD
  SCHED: CosineAnnealingLR
  STEPS:
  - 40
  - 90
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 10
  FLIP:
    ENABLED: false
  IMS_PER_BATCH: 128
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3
  ROC:
    ENABLED: false

```
