### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by OroChippw** [JDAI-CV/fast-reid#720]
使用的设备是4060 LAPTOP
当我尝试可视化训练的AGW模型时候出现下述报错，显存足够但无法调用（可以完成训练，以及训练中的验证）
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.55 GiB (GPU 0; 8.00 GiB total capacity; 335.96 MiB already allocated; 5.59 GiB free; 1.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

我的运行脚本如下
`python demo/visualize_result.py --config-file logs/market1501/agw_R50/config.yaml --vis-label --dataset-name Market1501 --output logs/agw_R50_Market1501_vis --opts MODEL.WEIGHTS logs/market1501/agw_R50/model_best.pth`

我的config文件如下
```
CUDNN_BENCHMARK: true
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 0
  SAMPLER_TRAIN: NaiveIdentitySampler
  SET_WEIGHT: []
DATASETS:
  COMBINEALL: false
  NAMES:
  - Market1501
  TESTS:
  - Market1501
INPUT:
  AFFINE:
    ENABLED: false
  AUGMIX:
    ENABLED: false
    PROB: 0.0
  AUTOAUG:
    ENABLED: false
    PROB: 0.0
  CJ:
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    ENABLED: false
    HUE: 0.1
    PROB: 0.5
    SATURATION: 0.1
  CROP:
    ENABLED: false
    RATIO:
    - 0.75
    - 1.3333333333333333
    SCALE:
    - 0.16
    - 1
    SIZE:
    - 224
    - 224
  FLIP:
    ENABLED: true
    PROB: 0.5
  PADDING:
    ENABLED: true
    MODE: constant
    SIZE: 10
  REA:
    ENABLED: true
    PROB: 0.5
    VALUE:
    - 123.675
    - 116.28
    - 103.53
  RPT:
    ENABLED: false
    PROB: 0.5
  SIZE_TEST:
  - 256
  - 128
  SIZE_TRAIN:
  - 256
  - 128
KD:
  EMA:
    ENABLED: false
    MOMENTUM: 0.999
  MODEL_CONFIG: []
  MODEL_WEIGHTS: []
MODEL:
  BACKBONE:
    ATT_DROP_RATE: 0.0
    DEPTH: 50x
    DROP_PATH_RATIO: 0.1
    DROP_RATIO: 0.0
    FEAT_DIM: 2048
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    PRETRAIN: true
    PRETRAIN_PATH: ''
    SIE_COE: 3.0
    STRIDE_SIZE:
    - 16
    - 16
    WITH_IBN: false
    WITH_NL: true
    WITH_SE: false
  DEVICE: cuda:0
  FREEZE_LAYERS: []
  HEADS:
    CLS_LAYER: Linear
    EMBEDDING_DIM: 0
    MARGIN: 0.0
    NAME: EmbeddingHead
    NECK_FEAT: before
    NORM: BN
    NUM_CLASSES: 751
    POOL_LAYER: GeneralizedMeanPooling
    SCALE: 1
    WITH_BNNECK: true
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 1.0
    CIRCLE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    COSFACE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    - TripletLoss
    TRI:
      HARD_MINING: false
      MARGIN: 0.0
      NORM_FEAT: false
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.120000000000005
  - 57.375
  QUEUE_SIZE: 8192
  WEIGHTS: 'D:\\OroChiLab\\fast-reid\\logs\\market1501\\agw_R50\\model_best.pth'
OUTPUT_DIR: logs/market1501/agw_R50
SOLVER:
  AMP:
    ENABLED: true
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 30
  CLIP_GRADIENTS:
    CLIP_TYPE: norm
    CLIP_VALUE: 5.0
    ENABLED: false
    NORM_TYPE: 2.0
  DELAY_EPOCHS: 0
  ETA_MIN_LR: 1.0e-07
  FREEZE_ITERS: 0
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  MAX_EPOCH: 120
  MOMENTUM: 0.9
  NESTEROV: false
  OPT: Adam
  SCHED: MultiStepLR
  STEPS:
  - 40
  - 90
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 30
  FLIP:
    ENABLED: false
  IMS_PER_BATCH: 64
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3
  ROC:
    ENABLED: false
```
